GET http://localhost:3005/

###

POST https://event4u.online/
Content-Type: application/json

{
  "firstname": "Linda",
  "lastname": "Gustafsson",
  "password": "userPassword",
  "email": "hej@hejsan.se",
  "phoneNumber": "0"
}

